### ISSUE TITLE
"I accept the terms of use" on signup page is not translated

### ISSUE THREAD

**Issue by xi** [liqd/a4-meinberlin#503]
A translation exists, but it is not used.

**Comment by kleingeist** [comment]
Fixed with #523

**Comment by Janaba** [comment]
problems still exist in dashboard:
Bebauungsplanverfahren
start date
end date
office worker email

**Comment by Janaba** [comment]
on profile page there is a spelling mistake in the translation:

to follow or unfollow you should set a 'Haken' not a 'Hacken' :)

**Comment by xi** [comment]
should all be fixed now.
